//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookReader
    {
        public int id { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> ReaderId { get; set; }
        public Nullable<System.DateTime> TakeDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
